name: cs224n
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter_client
  - libsqlite
  - certifi
  - jedi
  - fqdn
  - notebook-shim
  - traitlets
  - pathspec
  - isort
  - uri-template
  - defusedxml
  - jsonpointer
  - filelock
  - prompt_toolkit
  - pthread-stubs
  - prompt-toolkit
  - python_abi
  - fonttools
  - libbrotlienc
  - nbformat
  - python-dateutil
  - pandas
  - cached_property
  - brotli-bin
  - pycparser
  - websocket-client
  - tqdm
  - xorg-libxau
  - nomkl
  - numpy
  - black-jupyter
  - mypy_extensions
  - pyparsing
  - libopenblas
  - libprotobuf
  - mpc
  - platformdirs
  - libexpat
  - brotli
  - typing_extensions
  - ptyprocess
  - pytorch
  - tokenize-rt
  - tomli
  - ipython
  - xz
  - jsonschema
  - libbrotlidec
  - networkx
  - pytz
  - jinja2
  - sentencepiece-spm
  - cycler
  - libpng
  - colorama
  - matplotlib-inline
  - libbrotlicommon
  - executing
  - pysocks
  - libgfortran5
  - send2trash
  - contourpy
  - jupyterlab_server
  - appnope
  - rpds-py
  - typing-extensions
  - ipykernel
  - pexpect
  - backcall
  - pip
  - gensim
  - requests
  - sentencepiece-python
  - parso
  - nbclient
  - libuv
  - terminado
  - psutil
  - tinycss2
  - black
  - overrides
  - munkres
  - zipp
  - libzlib
  - importlib_metadata
  - backports.functools_lru_cache
  - pyyaml
  - regex
  - mpmath
  - babel
  - tk
  - setuptools
  - zstd
  - argon2-cffi-bindings
  - docopt
  - python-json-logger
  - liblapack
  - jupyter_server_terminals
  - libblas
  - asttokens
  - jsonschema-with-format-nongpl
  - nest-asyncio
  - xorg-libxdmcp
  - decorator
  - importlib-metadata
  - debugpy
  - soupsieve
  - jupyter_core
  - smart_open
  - argon2-cffi
  - json5
  - tornado
  - gmp
  - webcolors
  - libgfortran
  - matplotlib
  - prometheus_client
  - pygments
  - async-lru
  - anyio
  - readline
  - stack_data
  - wheel
  - jsonschema-specifications
  - brotli-python
  - markupsafe
  - libsodium
  - kiwisolver
  - libdeflate
  - flit-core
  - mistune
  - pure_eval
  - typing_utils
  - openssl
  - scikit-learn
  - wcwidth
  - jupyterlab
  - webencodings
  - llvm-openmp
  - isoduration
  - ncurses
  - idna
  - lcms2
  - pandocfilters
  - nbconvert-core
  - six
  - cffi
  - ca-certificates
  - pickleshare
  - libffi
  - beautifulsoup4
  - pillow
  - pooch
  - python-fastjsonschema
  - exceptiongroup
  - arrow
  - nltk
  - sniffio
  - jupyter-lsp
  - cached-property
  - packaging
  - libwebp-base
  - zeromq
  - click
  - entrypoints
  - libabseil
  - python-tzdata
  - libcblas
  - sympy
  - mpfr
  - attrs
  - threadpoolctl
  - yaml
  - libcxx
  - tzdata
  - charset-normalizer
  - pkgutil-resolve-name
  - importlib_resources
  - scipy
  - gmpy2
  - backports
  - bzip2
  - python=3.11
  - lerc
  - bleach
  - joblib
  - sleef
  - urllib3
  - libjpeg-turbo
  - rfc3986-validator
  - comm
  - sentencepiece
  - freetype
  - rfc3339-validator
  - pyzmq
  - libtiff
  - jupyter_server
  - openjpeg
  - ruff
  - jupyterlab_pygments
  - matplotlib-base
  - libxcb
  - referencing
  - libsentencepiece
  - jupyter_events
  - tensorboard
  - sacrebleu
